using System.Collections;
using System.Collections.Generic;
using Unity.XR.CoreUtils;
using UnityEngine;
using UnityEngine.XR.Interaction.Toolkit;

public class CharacterControllerHelper : MonoBehaviour
{
    private XROrigin XROrigin;
    private CharacterController CharacterController;
    private CharacterControllerDriver Driver;

    void Start()
    {
        XROrigin = GetComponent<XROrigin>();
        CharacterController = GetComponent<CharacterController>();
        Driver = GetComponent<CharacterControllerDriver>();
    }

    void Update()
    {
        UpdateCharacterController();
    }

    /// <summary>
    /// Updates the <see cref="CharacterController.height"/> and <see cref="CharacterController.center"/>
    /// based on the camera's position.
    /// </summary>
    protected virtual void UpdateCharacterController()
    {
        if (XROrigin == null || CharacterController == null)
            return;

        var height = Mathf.Clamp(XROrigin.CameraInOriginSpaceHeight, Driver.minHeight, Driver.maxHeight);

        Vector3 center = XROrigin.CameraInOriginSpacePos;
        center.y = height / 2f + CharacterController.skinWidth;

        CharacterController.height = height;
        CharacterController.center = center;
    }
}
